version: '2'

services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    build: 
      context: https://github.com/wurstmeister/kafka-docker.git
      dockerfile: Dockerfile
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME:  127.0.0.1
      KAFKA_CREATE_TOPICS: "test:1:1"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  api:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "80:80"
    environment: 
      KAFKA_HOST : kafka:9092
      KAFKA_TOPIC : test